#Пример комментария (не должен быть в output.cfg)

#Примеры констант:
host: localhost
port: 5432

#Пример массива со словами:
colors:
  - red
  - green
  - blue
  - yellow

#Пример массива со значениями:
numbers:
  - 3242
  - 4242.32
  - 32.311

#Пример массива в массиве:
teams:
  - name: Team A
    members:
      - Alice
      - Bob
  - name: Team B
    members:
      - Charlie
      - Dima

#Пример словаря:
person:
  name: John Doe
  age: 30
  is_employee: true
  #Массив в словаре
  hobbies:
  - reading
  - swimming
  #Словарь в словаре
  address:
    street: 123 Main St
    city: Anytown

#Вычисление константного выражения на этапе трансляции:
constants:
  a: 3
  b: 4
  c: 1.123
  d: 2.12


calculations:
  sum:
    a+b: "a+b"
  sub:
    a-b: "a-b"
  mul:
    a*b: "a*b"
  div:
    a/b: "a/b"
  paralel:
    (a+b)*(a-b): "a+b * a-b"
